### ISSUE TITLE
Info; ndscheduler make simple fail

### ISSUE THREAD

**Issue by LaikaN57** [Nextdoor/ndscheduler#102]
**From external [redacted]:**

make simple times out:

```
  Running command git clone --filter=blob:none --quiet git://github.com/djacobs/PyAPNs.git /private/var/folders/t_/rc213wmx66g3r6zwqfvrh3cc0000gn/T/pip-install-o58t0_l9/pyapns_3e89f11475f9455fa0fea75da18a3993
  fatal: unable to connect to [github.com](http://github.com/):
  [github.com](http://github.com/)[0: 140.82.113.4]: errno=Operation timed out
```

I am able to clone from the command line with:

```
git clone --filter=blob:none --quiet https://github.com/djacobs/PyAPNs.git
```

But, changing requirements.txt 

```
< git+git://github.com/djacobs/PyAPNs.git#egg=PyAPNs
---
> git+https://github.com/djacobs/PyAPNs.git
```

Leads to issue with ‘tornado not installed’.

Any help.?

**Comment by schaferk** [comment]
started over with fresh clone.

BLUF: sandbox violation (OSX M1)

make simple

error: Setup script exited with error: SandboxViolation: mkdir('/Users/schaferk/Library/Caches/com.apple.python/private/var/folders/t_/rc213wmx66g3r6zwqfvrh3cc0000gn/T/easy_install-edv5_c8m', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

make[1]: *** [install] Error 1
make: *** [simple] Error 2

'sandbox violation' seems to be a common occurrence, as there are many instances shown in a google search

**Comment by LaikaN57** [comment]
Cleaning up my issues. Please open a new issue if this is still impacting.
