### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by ibnbay00** [Nextdoor/ndscheduler#24]
I test error on running batch/shell file.
but job execution status is "Success" and Result is:
`{
    "returncode": 1
}`
Can I print the error on shell script to result trough a Job argument?

And what best practice argument for job shell script?

**Comment by hnq90** [comment]
@ibnbay00 You should raise an exception when command's status code is different than 0.

**Comment by sabw8217** [comment]
Yes, raise an exception if you want the job to be marked as a failure.
