### ISSUE TITLE
Add chaining job

### ISSUE THREAD

**Issue by ibnbay00** [Nextdoor/ndscheduler#27]
How to add chaining job?
After job1 is finish then job2 start

**Comment by Stovoy** [comment]
Outside of the scheduler itself; make job1 publish job2.

**Comment by ibnbay00** [comment]
Hi, @swaggy, can u explain to be more clear?
How the step to produce it...

Thanks

**Comment by sabw8217** [comment]
This seems like something you would use a distributed task queue or perhaps something like Airflow for, not ndscheduler.
