### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by tschm** [Nextdoor/ndscheduler#29]
Collecting ndscheduler from git+https://github.com/Nextdoor/ndscheduler.git#egg=ndscheduler
  Cloning https://github.com/Nextdoor/ndscheduler.git to /tmp/pip-build-mm359amx/ndscheduler
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mm359amx/ndscheduler/setup.py", line 65, in <module>
        long_description=open('README.md').read(),
      File "/home/thomas/production/env/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 495: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mm359amx/ndscheduler/

**Comment by hnq90** [comment]
@tschm Did you try to run it on Python 2.7 instead of 3.x?

**Comment by tschm** [comment]
We don't do Python 2.7

**Comment by akusei** [comment]
I'm having the exact same error using python 3.6.5 and pip version 18.0. This is almost a year old issue, is there any movement on this?

**Comment by sabw8217** [comment]
@akusei can you share the output of `python -c 'import sys; print(sys.getdefaultencoding())'`?

I think you may have overwritten the default system encoding to be `ascii` instead of `utf8` and for some reason there is a smart quote in the `README.md`.
