### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by EmFl** [Nextdoor/ndscheduler#33]
Hello,

I see that no commits have been made recently and am wondering about the status of this project. This looks like the tool I would need to use but I'm wondering if that's smart seeing the activity. Is this not in used anymore at nextdoor ? 
What are the alternatives if any ? 
Thanks !

**Comment by kartick** [comment]
Hi @EmFl,

I took the risk, and started using it, despite no recent updates and sporadic responses by author to issues. So far, no major issues in my installation and it is chugging along nicely. Not sure what your use case is, but if you are looking for choices, this is fresh off HN today: https://news.ycombinator.com/item?id=17030102 and the comments refer to Luigi (which I looked into before settling on `ndscheduler`), Airflow and Singer.

Thanks,
+Kartic

**Comment by EmFl** [comment]
Thanks @kartick ! I looked at that HN discussion but it seems that every solution is overkill for my use case. I don't need to move thousands of terabytes or aggregate data from multiple sources. My main need for now is to be able to start about 20 python scripts at different interval but I'm really looking for the reporting capabilities of these frameworks. I want something that allow us to see from a web page the last status of the jobs, the next scheduled run, and eventually cancel/reschedule from that same web page.
We were planning on using rundeck for that but their scheduler for now is not good enough.
I could do it with cron and a custom reporting page but I'm sure that this is already covered by a lot of tools out there. Didn't think it would be so hard to find the right one.
It feels weird starting a project knowing that the development has already stopped even though ndscheduler seems like the most close to what I want ...Maybe airflow on a single node as one of the reply on HN mentionned , I think it's the only one with the reporting capabilities I need (ie web page with jobs etc.) ... Definitely overkill but I'm at least we'll benefit from the active community around it...

How long have you been using ndscheduler kartick ?

**Comment by pjanakiraman** [comment]
Hi @EmFl - I'm one of the co-founders and CTO over at Nextdoor.  We still use ndscheduler internally here and run over 450 scheduled jobs through the service.  It's a critical part of our infrastructure, and so far we've had no problems with it operationally.  Admittedly, we developed this to be very simple, and while we haven't been actively adding new capabilities, it's still very much in use!

**Comment by EmFl** [comment]
I'm glad to hear that ! In that case it's definitely the first one I'll take an in-depth look at.
Thanks for the reply and for having contributed this to the world ! :)
