### ISSUE TITLE
Not able to override default settings

### ISSUE THREAD

**Issue by noqcks** [Nextdoor/ndscheduler#35]
We're trying to alter the setting `JOB_MAX_INSTANCES`, but not having any luck.

Dockerfile
```
FROM python:2-alpine3.7

RUN apk update && apk add git postgresql-dev gcc python-dev musl-dev

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

ENV NDSCHEDULER_SETTINGS_MODULE=settings

ADD . .

CMD ["python", "scheduler.py"]
```

settings.py
```
JOB_MAX_INSTANCES = 10
```

scheduler.py
```
"""Run the scheduler process."""
from ndscheduler.server import server

class Tassadar(server.SchedulerServer):
  pass

if __name__ == "__main__":
    Tassadar.run()
```

And we boot up the container and try to run more than 3 instances:

```ndscheduler.core.scheduler_manager - WARNING - Execution of job "REDACTED (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='0'], next run at: 2018-07-13 04:00:00 UTC)" skipped: maximum number of running instances reached (3)```

Any ideas? I would expect it to not limit out at 3 any more, but rather 10.

Thanks!

**Comment by kartick** [comment]
Hi,

Are you sure your `settings.py` is being read?

We run NDS via supervisor, and config looks like this:

```
[program:scheduler]
directory=/scheduler
command=python scheduler/scheduler.py
environment=PYTHONPATH="scheduler:${PYTHONPATH}",NDSCHEDULER_SETTINGS_MODULE=settings,SCHEDULER_DATA_ROOT=/scheduler/data
autostart=true
autorestart=true
startretries=5
exitcodes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
```

Our custom `settings.py` is in the `/scheduler` directory and it is sucked in using the `NDSCHEDULER_SETTINGS_MODULE` environment variable.

**Comment by sabw8217** [comment]
@noqcks can you share the rest of the logs you see on startup? As @kartick is suggesting, the likely problem is that your settings file is not being loaded at all because it is not on `sys.path`.

**Comment by noqcks** [comment]
Ahhh that was it.
