### ISSUE TITLE
Is it possible to backup ndscheduler jobs? 

### ISSUE THREAD

**Issue by noqcks** [Nextdoor/ndscheduler#36]
I have a over 50 jobs running in ndscheduler running and want to run them on another instance with a new hard drive.

How do I retain my job schedule? Is it possible?

**Comment by kartick** [comment]
@noqcks - If your jobs are stored in a database, you should be able to backup your DB, and restore it on your instance (or better use a centralized DB) and NDS can pick up your jobs there. If you are asking about moving _running_ jobs on to a new node, that's not possible with NDS.

In my case, in my `server.SchedulerServer` subclass, the code reads jobs from a JSON file (for version control purposes) and puts them in a SQLite DB. You could do something similar, but store it in a central DB?

**Comment by noqcks** [comment]
Ahh true. I didn't fully understand that database options were customizable. 

For anyone reading this in the future, db options here: https://github.com/Nextdoor/ndscheduler/blob/master/ndscheduler/default_settings.py#L47-L83
