### ISSUE TITLE
Validate return status for shell scripts

### ISSUE THREAD

**Issue by nsoria1** [Nextdoor/ndscheduler#40]
Hi team, thanks for sharing this tool.

I would like to know where should I modify the python code to evaluate the status code from shell scripts to make it fail if it is different than zero.

Thanks!
Nicolas.

**Comment by sabw8217** [comment]
Somewhere in the `run` method of the `Job` subclass you are using. For example, in the sample jobs, you would need to do something with the return value of the `call` function:
https://github.com/Nextdoor/ndscheduler/blob/master/simple_scheduler/jobs/shell_job.py#L24
