### ISSUE TITLE
Actually publish to PyPI

### ISSUE THREAD

**Issue by mcandre** [Nextdoor/ndscheduler#44]
It's rather easy, see https://github.com/mcandre/liquidnitrogen for an example PyPI-ready package structure.

**Comment by sabw8217** [comment]
@mrterry is working on it: https://github.com/Nextdoor/ndscheduler/pull/46

**Comment by mrterry** [comment]
I've cut v0.3 and it is currently published on PyPI.  https://pypi.org/project/ndscheduler/  This is simply a snapshot of master.  I haven't done any QA or additional testing.

I haven't (and won't) publish any old releases, but subsequent releases will get automatically published to PyPI when we cut a release on Github.
