### ISSUE TITLE
Implimentation

### ISSUE THREAD

**Issue by SimplySynced** [Nextdoor/ndscheduler#45]
Hello, I'm building an aquarium controller that is open sourced and was looking to build a scheduler into it.  It is a flask app and I was wondering if you have an example of this being used in a flask app.  Does this need to run separate from the app and then the app can use the API to communicate with it back and forth?  Appreciate it.

**Comment by sabw8217** [comment]
I'm not sure how using this with Flask would work, this is a Tornado app. I don't know much about Flask but I'm pretty sure it is a blocking framework, not one that can be run in an Tornado event loop. If you can figure out how to run Flask inside Tornado you could try overriding some of the server code in https://github.com/Nextdoor/ndscheduler/blob/master/ndscheduler/server/server.py (or mapping the URLs in your own Tornado server).

You could also run it as a separate server and use the API.

If you want something that can be used as a scheduler but could be run from inside a Flask app, you might want to look at [APScheduler](https://apscheduler.readthedocs.io/en/latest/) which is what `ndscheduler` is built on.
