### ISSUE TITLE
Make script fails on Windows

### ISSUE THREAD

**Issue by thatblairguy** [Nextdoor/ndscheduler#6]
Running `make simple` in a Windows environment, using Cygwinyields an error when it attempts to execute the .venv/bin/activate command in the init target.

```
. .venv/bin/activate && .venv/bin/pip install flake8
/bin/bash: .venv/bin/activate: No such file or directory
Makefile:10: recipe for target 'init' failed
make[2]: *** [init] Error 1`
make[2]: Leaving directory '/cygdrive/c/Nextdoor/ndscheduler'
Makefile:24: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/cygdrive/c/Nextdoor/ndscheduler'
Makefile:36: recipe for target 'simple' failed
```

The initial difficulty is that in a Windows environment, the virtualenv command doesn't create a .venv/bin directory. Instead, the executables are placed in: .venv/Scripts.  (As of Python 2.7.2.)

The PYTHON, PIP and SOURCE_VENV variables must be changed to reflect the .venv/Scripts location.  e.g.

```
PYTHON=.venv/Scripts/python
PIP=.venv/Scripts/pip
SOURCE_VENV=.venv/Scripts/activate
```

This change is not sufficient to resolve the problem. The virtualenv command installs activate as a .bat file instead of a .exe.  The bash shell doesn't  know to look for .bat files, and the command fails.  Changing the SOURCE_VENV variable to reference activate.bat (with the extension) allows activate to be found, however bash doesn't know how to interpret the file, and the script still fails.

**Comment by wenbinf** [comment]
Thanks for reporting this.

However, we don't plan to support Windows for now. This project mainly target for Mac OS X and Linux -- Sorry we should've made it clear in the README.md file.

**Comment by thatblairguy** [comment]
That's unfortunate.  We did discover that running `setup.py install` does allow the server to run (I've been playing with it today in fact).  That seems a bit simpler than the makefile, and perhaps more cross-platform as well.
